"""Definicion del enlace a la Base de Datos."""
DATA_BASE = "./config/geeks_hub.db"
SUSCRIPTION = "Suscripcion"
FILM = "Pelicula"
SERIES = "Serie"
ACCOUNT = "Cuenta"
PROFILE = "Perfil"
HISTORY = "Historial"
FAVORITES = "Favoritos"
FAVORITES_CONTENT = "Contenido_Favorito"
